import { boolean, date, integer, jsonb, pgEnum, pgTable, text, timestamp, uuid, varchar } from "drizzle-orm/pg-core";

export const recordStatus = pgEnum("record_status", ["draft", "pending", "approved", "in_progress", "on_hold", "completed", "cancelled"]);
const audit = { createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() };

export const customers = pgTable("customers", { id: uuid("id").defaultRandom().primaryKey(), code: varchar("code", { length: 40 }).notNull().unique(), name: varchar("name", { length: 200 }).notNull(), email: varchar("email", { length: 320 }), phone: varchar("phone", { length: 50 }), address: text("address"), active: boolean("active").default(true).notNull(), ...audit });
export const salesOrders = pgTable("sales_orders", { id: uuid("id").defaultRandom().primaryKey(), orderNumber: varchar("order_number", { length: 60 }).notNull().unique(), customerId: uuid("customer_id").references(() => customers.id), customerReference: varchar("customer_reference", { length: 120 }), requiredDate: date("required_date"), status: recordStatus("status").default("draft").notNull(), currency: varchar("currency", { length: 3 }).default("MYR").notNull(), notes: text("notes"), ...audit });
export const salesOrderItems = pgTable("sales_order_items", { id: uuid("id").defaultRandom().primaryKey(), salesOrderId: uuid("sales_order_id").references(() => salesOrders.id, { onDelete: "cascade" }).notNull(), lineNumber: integer("line_number").notNull(), partNumber: varchar("part_number", { length: 100 }).notNull(), description: text("description"), quantity: integer("quantity").notNull(), unitPriceMinor: integer("unit_price_minor"), ...audit });
export const processPlans = pgTable("process_plans", { id: uuid("id").defaultRandom().primaryKey(), planNumber: varchar("plan_number", { length: 60 }).notNull().unique(), partNumber: varchar("part_number", { length: 100 }).notNull(), revision: varchar("revision", { length: 20 }).default("A").notNull(), status: recordStatus("status").default("draft").notNull(), steps: jsonb("steps").$type<Array<{ operation: string; workCenter: string; sequence: number }>>().default([]).notNull(), ...audit });
export const manufacturingOrders = pgTable("manufacturing_orders", { id: uuid("id").defaultRandom().primaryKey(), orderNumber: varchar("order_number", { length: 60 }).notNull().unique(), salesOrderId: uuid("sales_order_id").references(() => salesOrders.id), processPlanId: uuid("process_plan_id").references(() => processPlans.id), partNumber: varchar("part_number", { length: 100 }).notNull(), quantity: integer("quantity").notNull(), completedQuantity: integer("completed_quantity").default(0).notNull(), plannedStart: date("planned_start"), plannedFinish: date("planned_finish"), priority: varchar("priority", { length: 20 }).default("normal").notNull(), status: recordStatus("status").default("draft").notNull(), notes: text("notes"), ...audit });
export const machines = pgTable("machines", { id: uuid("id").defaultRandom().primaryKey(), code: varchar("code", { length: 60 }).notNull().unique(), name: varchar("name", { length: 200 }).notNull(), workCenter: varchar("work_center", { length: 120 }), status: varchar("status", { length: 30 }).default("available").notNull(), capacityPerShift: integer("capacity_per_shift"), ...audit });
export const inventoryItems = pgTable("inventory_items", { id: uuid("id").defaultRandom().primaryKey(), partNumber: varchar("part_number", { length: 100 }).notNull().unique(), description: text("description").notNull(), unit: varchar("unit", { length: 20 }).default("pcs").notNull(), quantityOnHand: integer("quantity_on_hand").default(0).notNull(), reorderPoint: integer("reorder_point").default(0).notNull(), lotNumber: varchar("lot_number", { length: 100 }), location: varchar("location", { length: 120 }), ...audit });
export const procurementRequests = pgTable("procurement_requests", { id: uuid("id").defaultRandom().primaryKey(), requestNumber: varchar("request_number", { length: 60 }).notNull().unique(), description: text("description").notNull(), quantity: integer("quantity").notNull(), requiredDate: date("required_date"), supplierName: varchar("supplier_name", { length: 200 }), status: recordStatus("status").default("pending").notNull(), requestedBy: varchar("requested_by", { length: 200 }), ...audit });
export const qualityInspections = pgTable("quality_inspections", { id: uuid("id").defaultRandom().primaryKey(), inspectionNumber: varchar("inspection_number", { length: 60 }).notNull().unique(), kind: varchar("kind", { length: 20 }).notNull(), manufacturingOrderId: uuid("manufacturing_order_id").references(() => manufacturingOrders.id), partNumber: varchar("part_number", { length: 100 }).notNull(), lotNumber: varchar("lot_number", { length: 100 }), quantityInspected: integer("quantity_inspected").default(0).notNull(), quantityAccepted: integer("quantity_accepted").default(0).notNull(), status: recordStatus("status").default("pending").notNull(), findings: jsonb("findings").$type<Record<string, unknown>>().default({}).notNull(), inspectedAt: timestamp("inspected_at", { withTimezone: true }), ...audit });
export const nonConformanceReports = pgTable("non_conformance_reports", { id: uuid("id").defaultRandom().primaryKey(), ncrNumber: varchar("ncr_number", { length: 60 }).notNull().unique(), source: varchar("source", { length: 100 }).notNull(), partNumber: varchar("part_number", { length: 100 }).notNull(), description: text("description").notNull(), disposition: varchar("disposition", { length: 100 }), status: recordStatus("status").default("pending").notNull(), ...audit });
export const systemEvents = pgTable("system_events", { id: uuid("id").defaultRandom().primaryKey(), actorId: varchar("actor_id", { length: 100 }), action: varchar("action", { length: 100 }).notNull(), entityType: varchar("entity_type", { length: 100 }).notNull(), entityId: varchar("entity_id", { length: 100 }), details: jsonb("details").$type<Record<string, unknown>>().default({}).notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).defaultNow().notNull() });

export const user = pgTable("user", { id: text("id").primaryKey(), name: text("name").notNull(), email: text("email").notNull().unique(), emailVerified: boolean("email_verified").default(false).notNull(), image: text("image"), role: text("role").default("user"), mesRole: text("mes_role").default("OPERATOR").notNull(), banned: boolean("banned").default(false), banReason: text("ban_reason"), banExpires: timestamp("ban_expires", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const session = pgTable("session", { id: text("id").primaryKey(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), token: text("token").notNull().unique(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(), ipAddress: text("ip_address"), userAgent: text("user_agent"), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), activeOrganizationId: text("active_organization_id"), impersonatedBy: text("impersonated_by") });
export const account = pgTable("account", { id: text("id").primaryKey(), accountId: text("account_id").notNull(), providerId: text("provider_id").notNull(), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), accessToken: text("access_token"), refreshToken: text("refresh_token"), idToken: text("id_token"), accessTokenExpiresAt: timestamp("access_token_expires_at", { withTimezone: true }), refreshTokenExpiresAt: timestamp("refresh_token_expires_at", { withTimezone: true }), scope: text("scope"), password: text("password"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull() });
export const verification = pgTable("verification", { id: text("id").primaryKey(), identifier: text("identifier").notNull(), value: text("value").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(), updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow() });
export const organization = pgTable("organization", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), logo: text("logo"), metadata: text("metadata"), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const member = pgTable("member", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }), role: text("role").default("member").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const invitation = pgTable("invitation", { id: text("id").primaryKey(), organizationId: text("organization_id").notNull().references(() => organization.id, { onDelete: "cascade" }), email: text("email").notNull(), role: text("role"), status: text("status").default("pending").notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), inviterId: text("inviter_id").notNull().references(() => user.id), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
